export const MOOD_ICON_OPTIONS = [
  { label: "Angry face with horns", value: "/mood-icons/angry-face-with-horns.svg" },
  { label: "Angry face", value: "/mood-icons/angry-face.svg" },
  { label: "Anguished face", value: "/mood-icons/anguished-face.svg" },
  { label: "Anxious face with sweat", value: "/mood-icons/anxious-face-with-sweat.svg" },
  { label: "Astonished face", value: "/mood-icons/astonished-face.svg" },
  { label: "Beaming face with smiling eyes", value: "/mood-icons/beaming-face-with-smiling-eyes.svg" },
  { label: "Clown face", value: "/mood-icons/clown-face.svg" },
  { label: "Cold face", value: "/mood-icons/cold-face.svg" },
  { label: "Confounded face", value: "/mood-icons/confounded-face.svg" },
  { label: "Confused face", value: "/mood-icons/confused-face.svg" },
  { label: "Cowboy hat face", value: "/mood-icons/cowboy-hat-face.svg" },
  { label: "Crying face", value: "/mood-icons/crying-face.svg" },
  { label: "Disappointed face", value: "/mood-icons/disappointed-face.svg" },
  { label: "Disguised face", value: "/mood-icons/disguised-face.svg" },
  { label: "Dizzy face", value: "/mood-icons/dizzy-face.svg" },
  { label: "Dotted line face", value: "/mood-icons/dotted-line-face.svg" },
  { label: "Downcase face with sweat", value: "/mood-icons/downcase-face-with-sweat.svg" },
  { label: "Drooling face", value: "/mood-icons/drooling-face.svg" },
  { label: "Exploding head", value: "/mood-icons/exploding-head.svg" },
  { label: "Expressionless face", value: "/mood-icons/expressionless-face.svg" },
  { label: "Face blowing a kiss", value: "/mood-icons/face-blowing-a-kiss.svg" },
  { label: "Face exhaling", value: "/mood-icons/face-exhaling.svg" },
  { label: "Face holding back tears", value: "/mood-icons/face-holding-back-tears.svg" },
  { label: "Face in clouds", value: "/mood-icons/face-in-clouds.svg" },
  { label: "Face savoring food", value: "/mood-icons/face-savoring-food.svg" },
  { label: "Face screaming in fear", value: "/mood-icons/face-screaming-in-fear.svg" },
  { label: "Face vomiting", value: "/mood-icons/face-vomiting.svg" },
  { label: "Face with diagonal mouth", value: "/mood-icons/face-with-diagonal-mouth.svg" },
  { label: "Face with hand over mouth", value: "/mood-icons/face-with-hand-over-mouth.svg" },
  { label: "Face with head bandage", value: "/mood-icons/face-with-head-bandage.svg" },
  { label: "Face with medical mask", value: "/mood-icons/face-with-medical-mask.svg" },
  { label: "Face with monocle", value: "/mood-icons/face-with-monocle.svg" },
  { label: "Face with open eyes and hand over mouth", value: "/mood-icons/face-with-open-eyes-and-hand-over-mouth.svg" },
  { label: "Face with open mouth", value: "/mood-icons/face-with-open-mouth.svg" },
  { label: "Face with peeking eye", value: "/mood-icons/face-with-peeking-eye.svg" },
  { label: "Face with raised eyebrow", value: "/mood-icons/face-with-raised-eyebrow.svg" },
  { label: "Face with rolling eyes", value: "/mood-icons/face-with-rolling-eyes.svg" },
  { label: "Face with spiral eyes", value: "/mood-icons/face-with-spiral-eyes.svg" },
  { label: "Face with steam from nose", value: "/mood-icons/face-with-steam-from-nose.svg" },
  { label: "Face with symbols on mouth", value: "/mood-icons/face-with-symbols-on-mouth.svg" },
  { label: "Face with tears of joy", value: "/mood-icons/face-with-tears-of-joy.svg" },
  { label: "Face with thermometer", value: "/mood-icons/face-with-thermometer.svg" },
  { label: "Face with tongue", value: "/mood-icons/face-with-tongue.svg" },
  { label: "Face without mouth", value: "/mood-icons/face-without-mouth.svg" },
  { label: "Fearful face", value: "/mood-icons/fearful-face.svg" },
  { label: "Flushed face", value: "/mood-icons/flushed-face.svg" },
  { label: "Frowning face with open mouth", value: "/mood-icons/frowning-face-with-open-mouth.svg" },
  { label: "Frowning face", value: "/mood-icons/frowning-face.svg" },
  { label: "Grimacing face", value: "/mood-icons/grimacing-face.svg" },
  { label: "Grinning face with big eyes", value: "/mood-icons/grinning-face-with-big-eyes.svg" },
  { label: "Grinning face with smiling eyes", value: "/mood-icons/grinning-face-with-smiling-eyes.svg" },
  { label: "Grinning face with sweat", value: "/mood-icons/grinning-face-with-sweat.svg" },
  { label: "Grinning face", value: "/mood-icons/grinning-face.svg" },
  { label: "Grinning squinting face", value: "/mood-icons/grinning-squinting-face.svg" },
  { label: "Head shaking horizontally", value: "/mood-icons/head-shaking-horizontally.svg" },
  { label: "Head shaking vertically", value: "/mood-icons/head-shaking-vertically.svg" },
  { label: "Hot face", value: "/mood-icons/hot-face.svg" },
  { label: "Hugging face", value: "/mood-icons/hugging-face.svg" },
  { label: "Hushed face", value: "/mood-icons/hushed-face.svg" },
  { label: "Kissing face with closed eyes", value: "/mood-icons/kissing-face-with-closed-eyes.svg" },
  { label: "Kissing face with smiling eyes", value: "/mood-icons/kissing-face-with-smiling-eyes.svg" },
  { label: "Kissing face", value: "/mood-icons/kissing-face.svg" },
  { label: "Loudly crying face", value: "/mood-icons/loudly-crying-face.svg" },
  { label: "Lying face", value: "/mood-icons/lying-face.svg" },
  { label: "Melting face", value: "/mood-icons/melting-face.svg" },
  { label: "Mewing face", value: "/mood-icons/mewing-face.svg" },
  { label: "Money mouth face", value: "/mood-icons/money-mouth-face.svg" },
  { label: "Nauseated face", value: "/mood-icons/nauseated-face.svg" },
  { label: "Nerd face", value: "/mood-icons/nerd-face.svg" },
  { label: "Neutral face", value: "/mood-icons/neutral-face.svg" },
  { label: "Partying face", value: "/mood-icons/partying-face.svg" },
  { label: "Pensive face", value: "/mood-icons/pensive-face.svg" },
  { label: "Persevering face", value: "/mood-icons/persevering-face.svg" },
  { label: "Pile of poo", value: "/mood-icons/pile-of-poo.svg" },
  { label: "Pleading face", value: "/mood-icons/pleading-face.svg" },
  { label: "Pouting face", value: "/mood-icons/pouting-face.svg" },
  { label: "Relieved face", value: "/mood-icons/relieved-face.svg" },
  { label: "Robot", value: "/mood-icons/robot.svg" },
  { label: "Rolling on the floor laughing", value: "/mood-icons/rolling-on-the-floor-laughing.svg" },
  { label: "Sad but relieved face", value: "/mood-icons/sad-but-relieved-face.svg" },
  { label: "Saluting face", value: "/mood-icons/saluting-face.svg" },
  { label: "Shaking face", value: "/mood-icons/shaking-face.svg" },
  { label: "Shushing face", value: "/mood-icons/shushing-face.svg" },
  { label: "Skull", value: "/mood-icons/skull.svg" },
  { label: "Sleeping face", value: "/mood-icons/sleeping-face.svg" },
  { label: "Sleepy face", value: "/mood-icons/sleepy-face.svg" },
  { label: "Slightly frowning face", value: "/mood-icons/slightly-frowning-face.svg" },
  { label: "Slightly smiling face", value: "/mood-icons/slightly-smiling-face.svg" },
  { label: "Smiling face with halo", value: "/mood-icons/smiling-face-with-halo.svg" },
  { label: "Smiling face with heart-eyes", value: "/mood-icons/smiling-face-with-heart-eyes.svg" },
  { label: "Smiling face with hearts", value: "/mood-icons/smiling-face-with-hearts.svg" },
  { label: "Smiling face with horns", value: "/mood-icons/smiling-face-with-horns.svg" },
  { label: "Smiling face with smiling eyes", value: "/mood-icons/smiling-face-with-smiling-eyes.svg" },
  { label: "Smiling face with sunglasses", value: "/mood-icons/smiling-face-with-sunglasses.svg" },
  { label: "Smiling face with tear", value: "/mood-icons/smiling-face-with-tear.svg" },
  { label: "Smiling face", value: "/mood-icons/smiling-face.svg" },
  { label: "Smirking face", value: "/mood-icons/smirking-face.svg" },
  { label: "Sneezing face", value: "/mood-icons/sneezing-face.svg" },
  { label: "Squinting face with tongue", value: "/mood-icons/squinting-face-with-tongue.svg" },
  { label: "Star-struck", value: "/mood-icons/star-struck.svg" },
  { label: "Thinking face", value: "/mood-icons/thinking-face.svg" },
  { label: "Tired face", value: "/mood-icons/tired-face.svg" },
  { label: "Unamused face", value: "/mood-icons/unamused-face.svg" },
  { label: "Upside-down face", value: "/mood-icons/upside-down-face.svg" },
  { label: "Weary face", value: "/mood-icons/weary-face.svg" },
  { label: "Winking face with tongue", value: "/mood-icons/winking-face-with-tongue.svg" },
  { label: "Winking face", value: "/mood-icons/winking-face.svg" },
  { label: "Woozy face", value: "/mood-icons/woozy-face.svg" },
  { label: "Worried face", value: "/mood-icons/worried-face.svg" },
  { label: "Yawning face", value: "/mood-icons/yawning-face.svg" },
  { label: "Zany face", value: "/mood-icons/zany-face.svg" },
  { label: "Zipper-mouth face", value: "/mood-icons/zipper-mouth-face.svg" },
] as const;
