/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as FamiliesIndexRouteImport } from './routes/families.index'
import { Route as TestsNewRouteImport } from './routes/tests.new'
import { Route as QuestsNewRouteImport } from './routes/quests.new'
import { Route as QuestsQuestIdRouteImport } from './routes/quests.$questId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as FamiliesNewRouteImport } from './routes/families.new'
import { Route as FamiliesFamilyIdRouteImport } from './routes/families.$familyId'
import { Route as TestsTestIdTakeRouteImport } from './routes/tests.$testId.take'
import { Route as FamiliesFamilyIdDashboardRouteImport } from './routes/families_.$familyId.dashboard'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsNewRoute = TestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsNewRoute = QuestsNewRouteImport.update({
  id: '/quests/new',
  path: '/quests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsQuestIdRoute = QuestsQuestIdRouteImport.update({
  id: '/quests/$questId',
  path: '/quests/$questId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesNewRoute = FamiliesNewRouteImport.update({
  id: '/families/new',
  path: '/families/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesFamilyIdRoute = FamiliesFamilyIdRouteImport.update({
  id: '/families/$familyId',
  path: '/families/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdTakeRoute = TestsTestIdTakeRouteImport.update({
  id: '/tests/$testId/take',
  path: '/tests/$testId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesFamilyIdDashboardRoute =
  FamiliesFamilyIdDashboardRouteImport.update({
    id: '/families_/$familyId/dashboard',
    path: '/families/$familyId/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pets': typeof PetsRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/families/new': typeof FamiliesNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/new': typeof QuestsNewRoute
  '/tests/new': typeof TestsNewRoute
  '/families/': typeof FamiliesIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/families/$familyId/dashboard': typeof FamiliesFamilyIdDashboardRoute
  '/tests/$testId/take': typeof TestsTestIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pets': typeof PetsRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/families/new': typeof FamiliesNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/new': typeof QuestsNewRoute
  '/tests/new': typeof TestsNewRoute
  '/families': typeof FamiliesIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/tests': typeof TestsIndexRoute
  '/families/$familyId/dashboard': typeof FamiliesFamilyIdDashboardRoute
  '/tests/$testId/take': typeof TestsTestIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pets': typeof PetsRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/families/new': typeof FamiliesNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/new': typeof QuestsNewRoute
  '/tests/new': typeof TestsNewRoute
  '/families/': typeof FamiliesIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/families_/$familyId/dashboard': typeof FamiliesFamilyIdDashboardRoute
  '/tests/$testId/take': typeof TestsTestIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/calendar'
    | '/leaderboard'
    | '/login'
    | '/pets'
    | '/register'
    | '/rewards'
    | '/families/$familyId'
    | '/families/new'
    | '/profile/$userId'
    | '/quests/$questId'
    | '/quests/new'
    | '/tests/new'
    | '/families/'
    | '/quests/'
    | '/tests/'
    | '/families/$familyId/dashboard'
    | '/tests/$testId/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/calendar'
    | '/leaderboard'
    | '/login'
    | '/pets'
    | '/register'
    | '/rewards'
    | '/families/$familyId'
    | '/families/new'
    | '/profile/$userId'
    | '/quests/$questId'
    | '/quests/new'
    | '/tests/new'
    | '/families'
    | '/quests'
    | '/tests'
    | '/families/$familyId/dashboard'
    | '/tests/$testId/take'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/calendar'
    | '/leaderboard'
    | '/login'
    | '/pets'
    | '/register'
    | '/rewards'
    | '/families/$familyId'
    | '/families/new'
    | '/profile/$userId'
    | '/quests/$questId'
    | '/quests/new'
    | '/tests/new'
    | '/families/'
    | '/quests/'
    | '/tests/'
    | '/families_/$familyId/dashboard'
    | '/tests/$testId/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PetsRoute: typeof PetsRoute
  RegisterRoute: typeof RegisterRoute
  RewardsRoute: typeof RewardsRoute
  FamiliesFamilyIdRoute: typeof FamiliesFamilyIdRoute
  FamiliesNewRoute: typeof FamiliesNewRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  QuestsQuestIdRoute: typeof QuestsQuestIdRoute
  QuestsNewRoute: typeof QuestsNewRoute
  TestsNewRoute: typeof TestsNewRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
  FamiliesFamilyIdDashboardRoute: typeof FamiliesFamilyIdDashboardRoute
  TestsTestIdTakeRoute: typeof TestsTestIdTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/new': {
      id: '/tests/new'
      path: '/tests/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof TestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/new': {
      id: '/quests/new'
      path: '/quests/new'
      fullPath: '/quests/new'
      preLoaderRoute: typeof QuestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$questId': {
      id: '/quests/$questId'
      path: '/quests/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof QuestsQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/new': {
      id: '/families/new'
      path: '/families/new'
      fullPath: '/families/new'
      preLoaderRoute: typeof FamiliesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$familyId': {
      id: '/families/$familyId'
      path: '/families/$familyId'
      fullPath: '/families/$familyId'
      preLoaderRoute: typeof FamiliesFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/take': {
      id: '/tests/$testId/take'
      path: '/tests/$testId/take'
      fullPath: '/tests/$testId/take'
      preLoaderRoute: typeof TestsTestIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families_/$familyId/dashboard': {
      id: '/families_/$familyId/dashboard'
      path: '/families/$familyId/dashboard'
      fullPath: '/families/$familyId/dashboard'
      preLoaderRoute: typeof FamiliesFamilyIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PetsRoute: PetsRoute,
  RegisterRoute: RegisterRoute,
  RewardsRoute: RewardsRoute,
  FamiliesFamilyIdRoute: FamiliesFamilyIdRoute,
  FamiliesNewRoute: FamiliesNewRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  QuestsQuestIdRoute: QuestsQuestIdRoute,
  QuestsNewRoute: QuestsNewRoute,
  TestsNewRoute: TestsNewRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  QuestsIndexRoute: QuestsIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
  FamiliesFamilyIdDashboardRoute: FamiliesFamilyIdDashboardRoute,
  TestsTestIdTakeRoute: TestsTestIdTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
