/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as QuestsNewRouteImport } from './routes/quests.new'
import { Route as QuestsQuestIdRouteImport } from './routes/quests.$questId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsNewRoute = QuestsNewRouteImport.update({
  id: '/quests/new',
  path: '/quests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsQuestIdRoute = QuestsQuestIdRouteImport.update({
  id: '/quests/$questId',
  path: '/quests/$questId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/new': typeof QuestsNewRoute
  '/quests/': typeof QuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/new': typeof QuestsNewRoute
  '/quests': typeof QuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/new': typeof QuestsNewRoute
  '/quests/': typeof QuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quests/$questId' | '/quests/new' | '/quests/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quests/$questId' | '/quests/new' | '/quests'
  id: '__root__' | '/' | '/quests/$questId' | '/quests/new' | '/quests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestsQuestIdRoute: typeof QuestsQuestIdRoute
  QuestsNewRoute: typeof QuestsNewRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/new': {
      id: '/quests/new'
      path: '/quests/new'
      fullPath: '/quests/new'
      preLoaderRoute: typeof QuestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$questId': {
      id: '/quests/$questId'
      path: '/quests/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof QuestsQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestsQuestIdRoute: QuestsQuestIdRoute,
  QuestsNewRoute: QuestsNewRoute,
  QuestsIndexRoute: QuestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
